# Generated by Django 4.2.5 on 2023-09-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Subject',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CustUser',
            fields=[
                ('std_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('disability', models.CharField(choices=[('Physical', 'Physical'), ('Visual', 'Visual'), ('Hearing', 'Hearing'), ('Cognitive', 'Cognitive')], max_length=100)),
                ('accesstechnology', models.CharField(choices=[('Screen Reader', 'Screen Reader'), ('Braille Display', 'Braille Display'), ('Hearing Aids', 'Hearing Aids'), ('Voice Recognition', 'Voice Recognition')], max_length=50)),
                ('fav_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='f_sub', to='accounts.subjects')),
                ('weak_sub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='w_sub', to='accounts.subjects')),
            ],
        ),
    ]
