# Generated by Django 4.2.5 on 2023-09-20 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_student_accesstechnology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fav_subject',
            field=models.ForeignKey(default='Biology', on_delete=django.db.models.deletion.CASCADE, related_name='f_sub', to='accounts.subjects'),
        ),
        migrations.AlterField(
            model_name='student',
            name='weak_sub',
            field=models.ForeignKey(default='Biology', on_delete=django.db.models.deletion.CASCADE, related_name='w_sub', to='accounts.subjects'),
        ),
    ]
