# Generated by Django 4.2.5 on 2023-09-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_testscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='TestScore',
        ),
    ]
