# Generated by Django 4.2.5 on 2023-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_testscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscore',
            name='Score',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
