# Generated by Django 4.2.5 on 2023-09-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_testscore_answer_remove_testscore_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='answer',
            new_name='a1',
        ),
        migrations.AddField(
            model_name='questions',
            name='a2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='a3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='a4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_q', to='accounts.subjects'),
        ),
    ]
