# Generated by Django 4.2.5 on 2023-09-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_studentanswer_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('disability', models.CharField(choices=[('Physical', 'Physical'), ('Visual', 'Visual'), ('Hearing', 'Hearing'), ('Cognitive', 'Cognitive')], default='Physical', max_length=100)),
                ('accesstechnology', models.CharField(choices=[('Screen Reader', 'Screen Reader'), ('Braille Display', 'Braille Display'), ('Hearing Aids', 'Hearing Aids'), ('Voice Recognition', 'Voice Recognition')], default='Screen Reader', max_length=50)),
                ('fav_subject', models.ForeignKey(default='Biology', on_delete=django.db.models.deletion.CASCADE, related_name='f_sub', to='accounts.subjects')),
                ('weak_sub', models.ForeignKey(default='Biology', on_delete=django.db.models.deletion.CASCADE, related_name='w_sub', to='accounts.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='TestResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Math_Result', models.IntegerField()),
                ('Vowels', models.CharField(max_length=10)),
                ('Powerhouse_of_Cell', models.CharField(max_length=100)),
                ('Unit_of_Force', models.CharField(max_length=100)),
                ('Chemical_Symbol_of_Gold', models.CharField(max_length=10)),
                ('Father_of_the_Nation', models.CharField(max_length=100)),
                ('Founder_of_Computer', models.CharField(max_length=100)),
                ('Music_Notation_of_Piano', models.CharField(max_length=100)),
                ('Contour_Line_in_Drawing', models.CharField(max_length=100)),
                ('World_War_Started_Year', models.IntegerField()),
                ('Score', models.IntegerField()),
                ('Score_Category', models.CharField(max_length=20)),
                ('Std_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_test', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
