# Generated by Django 4.2.5 on 2023-09-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_student_testresultmodel_studentanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
