# Generated by Django 4.2.5 on 2023-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_studentanswer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fav_subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='weak_sub',
        ),
        migrations.AlterField(
            model_name='student',
            name='accesstechnology',
            field=models.CharField(choices=[('Screen Reader', 'Screen Reader'), ('Communication App', 'Communication App'), ('Hearing Aids', 'Hearing Aid'), ('Voice Recognition', 'Voice Recognition'), ('Wheelchair', 'Wheelchair'), ('Assistive Learning Tools', 'Assistive Learning Tools'), ('Text-to-Speech Software', 'Text-to-Speech Software'), ('Augmentative and Alternative Communication (AAC) Device', 'Augmentative and Alternative Communication (AAC) Device')], default='Screen Reader', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='disability',
            field=models.CharField(choices=[('Mobility Impairment', 'Mobility Impairment'), ('Visual Impairment', 'Visual Impairment'), ('Hearing Impairment', 'Hearing Impairment'), ('Learning Disability', 'Learning Disability'), ('Autism Spectrum Disorder', 'Autism Spectrum Disorder'), ('Speech Impairment', 'Speech Impairment'), ('Intellectual Disability', 'Intellectual Disability')], default='Mobility Impairment', max_length=100),
        ),
    ]
