# Generated by Django 4.2.5 on 2023-09-21 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_student_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
        migrations.CreateModel(
            name='TestResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Math_Result', models.IntegerField()),
                ('Vowels', models.CharField(max_length=10)),
                ('Powerhouse_of_Cell', models.CharField(max_length=100)),
                ('Unit_of_Force', models.CharField(max_length=100)),
                ('Chemical_Symbol_of_Gold', models.CharField(max_length=10)),
                ('Father_of_the_Nation', models.CharField(max_length=100)),
                ('Founder_of_Computer', models.CharField(max_length=100)),
                ('Music_Notation_of_Piano', models.CharField(max_length=100)),
                ('Contour_Line_in_Drawing', models.CharField(max_length=100)),
                ('World_War_Started_Year', models.IntegerField()),
                ('Score', models.IntegerField()),
                ('Score_Category', models.CharField(max_length=20)),
                ('Std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_test', to='accounts.student')),
            ],
        ),
    ]
