# Generated by Django 4.2.5 on 2023-09-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_student_category_remove_student_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='TestResultModel',
        ),
    ]
