# Generated by Django 4.2.5 on 2023-09-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_student_category_student_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctanswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='AnswerChoice',
        ),
        migrations.DeleteModel(
            name='CorrectAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
