# Generated by Django 4.2.5 on 2023-09-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_answer_category_question_studentanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='suggestion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
