# Generated by Django 4.2.5 on 2023-09-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_student_suggestion_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='student',
        ),
    ]
