# Generated by Django 4.2.5 on 2023-09-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_remove_suggestion_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.AddField(
            model_name='student',
            name='suggestion',
            field=models.TextField(null=True),
        ),
    ]
