# Generated by Django 4.2.5 on 2023-09-25 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_ag', to='accounts.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tes_ag', to='accounts.question')),
            ],
        ),
    ]
