# Generated by Django 4.2.5 on 2023-10-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='video',
            field=models.FileField(null=True, upload_to='suggested video'),
        ),
    ]
