# Generated by Django 4.2.5 on 2023-10-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_suggestion_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='audio',
            field=models.FileField(null=True, upload_to='suggested audio'),
        ),
    ]
