# Generated by Django 4.2.5 on 2023-10-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_suggestion_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
