# Generated by Django 4.2.5 on 2023-10-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_suggestion_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='audio',
            field=models.FileField(null=True, upload_to='suggested audio'),
        ),
        migrations.AddField(
            model_name='student',
            name='video',
            field=models.FileField(null=True, upload_to='suggested video'),
        ),
    ]
