# Generated by Django 4.2.5 on 2023-10-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_student_first_name_student_img_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='student image'),
        ),
    ]
