# Generated by Django 4.2.7 on 2023-12-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_studentanswer_cat_studentanswer_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='cat',
            new_name='category',
        ),
    ]
