# Generated by Django 4.2.7 on 2023-12-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_rename_cat_studentanswer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='suggested audio'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='suggested video'),
        ),
    ]
