# Generated by Django 4.2.7 on 2023-12-26 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_studentanswer_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='score',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='video',
        ),
        migrations.CreateModel(
            name='ScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='suggested video')),
                ('audio', models.FileField(blank=True, null=True, upload_to='suggested audio')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
