# Generated by Django 4.2.7 on 2023-12-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_remove_studentanswer_audio_remove_studentanswer_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='student',
            name='category',
        ),
        migrations.RemoveField(
            model_name='student',
            name='score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='suggestion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='video',
        ),
    ]
