# Generated by Django 4.2.7 on 2023-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_remove_student_audio_remove_student_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='fileopt'),
        ),
        migrations.AddField(
            model_name='question',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
