# Generated by Django 4.2.5 on 2023-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_answer_file_question_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='file',
            new_name='fileans',
        ),
        migrations.AlterField(
            model_name='question',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/files_que'),
        ),
    ]
