# Generated by Django 4.2.5 on 2024-01-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_answeraudio_answerimages_questionaudio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeraudio',
            name='text',
        ),
        migrations.RemoveField(
            model_name='answerimages',
            name='text',
        ),
        migrations.AddField(
            model_name='answeraudio',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/files_queaudioans'),
        ),
        migrations.AddField(
            model_name='answerimages',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='media/files_queimageans'),
        ),
    ]
