# Generated by Django 4.2.5 on 2024-01-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_remove_answeraudio_text_remove_answerimages_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaudio',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.types'),
        ),
        migrations.AddField(
            model_name='questionimages',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.types'),
        ),
    ]
