# Generated by Django 4.2.5 on 2024-01-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_questionaudio_type_questionimages_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeraudio',
            old_name='files',
            new_name='fileans',
        ),
        migrations.RenameField(
            model_name='answerimages',
            old_name='files',
            new_name='fileans',
        ),
    ]
