# Generated by Django 4.2.5 on 2024-01-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_alter_studentansweraudio_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='files',
        ),
    ]
