# Generated by Django 4.2.5 on 2024-01-07 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_remove_question_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.ForeignKey(default='Text', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.types'),
        ),
        migrations.AlterField(
            model_name='questionaudio',
            name='type',
            field=models.ForeignKey(default='Audio', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.types'),
        ),
        migrations.AlterField(
            model_name='questionimages',
            name='type',
            field=models.ForeignKey(default='Image', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.types'),
        ),
    ]
