# Generated by Django 5.1.4 on 2025-01-26 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('send_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='notes_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewedMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('viewed_date', models.DateTimeField(null=True)),
                ('read_date', models.DateTimeField(null=True)),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_view', to='home.messages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_msg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
