# Generated by Django 4.2.7 on 2023-12-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AlterField(
            model_name='notes',
            name='file',
            field=models.FileField(upload_to='media/notes'),
        ),
    ]
