# Generated by Django 4.2.7 on 2023-12-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_notes_user_alter_notes_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
