# Generated by Django 4.2.7 on 2023-12-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_student_first_name_alter_student_last_name'),
        ('home', '0005_notes_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.category'),
        ),
    ]
