# Generated by Django 5.0.3 on 2024-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_viewedmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='viewedmessages',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewedmessages',
            name='read_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='viewedmessages',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewedmessages',
            name='viewed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
